name: Deploy GitHub Pages

on:
  push:
    branches: ["main"] # Triggers deployment when you push to main
  workflow_dispatch:   # Allows manual trigger from the Actions tab

# Grants necessary permissions to issue a deployment token
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'app' # Uploads root directory (where index.html is located)

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
